version: '3'
services:

  locust:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/mnt/locust
    user: "${UID}:${GID}"
    command: >
      -f /mnt/locust/locustfile.py -H http://${TARGETHOST:-server}
      --users ${USERS:-500} --spawn-rate ${SPAWN:-10}
      --run-time ${RUNTIME:-2m}
      --autostart
      --autoquit 5
      --html /mnt/locust/users-${USERS:-500}_spawn-${SPAWN:-10}_python-${PYTHON:-3.6.12}_flavor-${FLAVOR:-buster}_aiohttp-${AIOHTTP:-3.7.3}_loop-${EVENTLOOP-asyncio}.html

  server:
    build:
      context: ./
      dockerfile: dockerfile
      target: server
      args:
        AIOHTTP: ${AIOHTTP:-3.7.3}
        PYTHON: ${PYTHON:-3.6.12}
        FLAVOR: ${FLAVOR:-buster}
        CT_TOTAL: ${CT_TOTAL:-1}
        CT_CONNECT: ${CT_CONNECT:-0.5}
        CT_SOCK_CONNECT: ${CT_SOCK_CONNECT:-0.5}
    environment:
      - EVENTLOOP=${EVENTLOOP-asyncio}

  spied-server:
    build:
      context: ./
      dockerfile: dockerfile
      target: spied-server
      args:
        AIOHTTP: ${AIOHTTP:-3.7.3}
        PYTHON: ${PYTHON:-3.6.12}
        FLAVOR: ${FLAVOR:-buster}
        CT_TOTAL: ${CT_TOTAL:-1}
        CT_CONNECT: ${CT_CONNECT:-0.5}
        CT_SOCK_CONNECT: ${CT_SOCK_CONNECT:-0.5}
    cap_add:
     - SYS_PTRACE
    volumes:
      - ./:/mnt/spy
    environment:
      - EVENTLOOP=${EVENTLOOP-asyncio}
    stop_grace_period: 2m

  proxied:
    build:
      context: ./
      dockerfile: dockerfile
      args:
        AIOHTTP: ${AIOHTTP:-3.7.3}
        PYTHON: ${PYTHON:-3.6.12}
        FLAVOR: ${FLAVOR:-buster}
    environment:
      - EVENTLOOP=${EVENTLOOP-asyncio}
